name = "Season"
author = "Pavelkoro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2ff68a3a18941b7ace4fd72b23d9141a4e9ffdbcd1c5fee981dcf98f99db815"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
