name = "Season"
author = "Pavelkoro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d70d4500109d57637a022c9de0ad4de5fd4c0b299f312c66c1b1f7ad3501db92"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
