name = "Season"
author = "Pavelkoro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed255606f42a94162394c4e8b43a92d028a507448d2c1a2825c8b45ae54507ff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
